name: MOVIELENS_DBT_PROJECT
version: 1.0.0
config-version: 2
profile: MOVIELENS_DBT_PROJECT
model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
models:
  MOVIELENS_DBT_PROJECT:
    +materialized: view
    dim:
      +materialized: table
    fct:
      +materialized: table
    marts:
      +materialized: table
    
